name: Fetch-Weather-Data
on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12 PM UTC (5:30 PM IST)
  workflow_dispatch:       # Manual trigger option

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install requests pandas
      - name: Fetch weather data
        run: python scripts/fetch_weather.py
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/raw/weather.csv
          git commit -m "Automated weather data update"
          git push