name: Weather-Pipeline
on:
  schedule:
    - cron: "0 12 * * *"  # Daily at 12 PM UTC
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install requests pandas scikit-learn mlflow joblib

      - name: Create folders
        run: mkdir -p data/raw data/processed models

      - name: Fetch weather data
        run: python scripts/fetch_weather.py

      - name: Process data
        run: python scripts/process_data.py

      - name: Train model
        run: python scripts/train.py

      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/ models/
          git commit -m "Auto-update: New weather data and model"
          git push
      - name: Deploy to Render (Optional)
        run: |
          pip install fastapi uvicorn
          uvicorn app.main:app --host 0.0.0.0 --port 8000